# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aca18bd12b53d186072c0bc0002a6a59fa3177a025ec445a4a852601c1d827373db94f451bdcf9a529f8453d63dea9e91b3e0c111795e5b41a120797352104c

test:
  secret_key_base: da9e104342a824b2c14c7a0f3908e01d405c42f1fd6bd9c47f7ded46dc193c942e5277e57feec336e859bfc4a0a1f53783286f5b28ca9d99900d38ed05a5dfed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
